### ISSUE TITLE
Inline ASM Required? Can't support in Vyper

### ISSUE THREAD

**Issue by scherrey** [enjin/erc-1155#15]
We're attempting to implement our first 1155 token using Vyper rather than Solidity. Noticed that your example code has some inline assembly in it. See https://github.com/enjin/erc-1155/blob/master/contracts/ERC1155.sol#L206  

I'm not entirely certain what the operation is supposed to be doing here or what, if any, Vyper function would provide the equivalent functionality. Inline assembly is not allowed in Vyper. I expect we definitely want to support Vyper in 1155.

**Comment by AC0DEM0NK3Y** [comment]
It's just pulling the return value out if it was returned. Here a lowlevel .call is being used rather than a straight function call so that the call to onERC1155Received doesn't revert the transaction automatically see https://solidity.readthedocs.io/en/v0.5.8/control-structures.html#error-handling-assert-require-revert-and-exceptions

In this ref function that is not really needed, it could be reverted straight away but as you can see in the 1155/721 hybrid this can be a useful technique (as this code wants to continue if it is also an erc721 but the .call fails). Note: this is not updated to latest 1155 spec by the looks of it, maybe @wighawag can let us know when it plans to be: https://github.com/pixowl/thesandbox-contracts/blob/master/src/Asset/ERC1155ERC721.sol#L679

I'm not sure if this type of thing is possible with Vyper I've never looked, but if you don't need hybridity it should be fine to just call the on1155Received function and require the return value is exact.

**Comment by AC0DEM0NK3Y** [comment]
@scherrey would it be helpful if I changed this impl to not use inline asm? I guess it would.

**Comment by AC0DEM0NK3Y** [comment]
Altered: https://github.com/enjin/erc-1155/commit/6147143eae3ecddcd4b6108c8496d96f4dc9d7a1

**Comment by wighawag** [comment]
I updated the code at https://github.com/pixowl/thesandbox-contracts to fit the spec

@scherrey Feel free to ask any question
