### ISSUE TITLE
A question about function create() and mint() in ERC1155Mintable.sol

### ISSUE THREAD

**Issue by KCHENPENGFEI** [enjin/erc-1155#18]
Hi, I have a question about the function `create()` and `mint()` in the file--ERC1155Mintable.sol.
In the function `create()`, `balances[_id][msg.sender] = _initialSupply;` sets the value of `balances[_id][msg.sender]` to ` _initialSupply`.But in the function `mint()`, `balances[_id][to] = quantity.add(balances[_id][to]);` shows that `balances[_id][to]` is be added, but `balances[_id][msg.sender]` is not be subtracted.
And in `emit TransferSingle(msg.sender, address(0x0), to, _id, quantity);`, why the _from address is "0x0"？

**Comment by skibitsky** [comment]
1. You are free to change this part, it isn't part of the standard. If you want to send initial token supply to someone else you can have something like this:
```js
function create(uint256 _initialSupply, address calldata _to, string calldata _uri) external returns(uint256 _id) {
    _id = ++nonce;
    creators[_id] = msg.sender;
    balances[_id][_to] = _initialSupply;
    emit TransferSingle(msg.sender, address(0x0), _to, _id, _initialSupply);
    if (bytes(_uri).length > 0)
        emit URI(_uri, _id);
}
```
This is implementation-specific part. Change it as you want.

2. Minting event sets _from to 0x0 in order to inform that it is a newly minted token. This is a common practice in token minting and coin mining. Moreover, you MUST do that by the  [EIP-1155 Specification](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1155.md#specification).
Same with burning tokens, `_to` must be zero address.

**Comment by KCHENPENGFEI** [comment]
@skibitsky thanks

**Comment by AC0DEM0NK3Y** [comment]
Great explanation @skibitsky. Closing the issue it looks to have been addressed.
